/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.InterfaceTipoDocumento;

import controlador.CITipoDocumento;
import java.util.List;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author reida
 */
public class InterfaceTipoDocumento extends javax.swing.JInternalFrame {

    CITipoDocumento ctrl;
    /**
     * Creates new form cadastroTipoDocumento
     */
    public InterfaceTipoDocumento(CITipoDocumento ctrl) {
        this.ctrl = ctrl;
        initComponents();
        panelTab.addChangeListener(new javax.swing.event.ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                limparInterfaceConsulta();
                preencherCmbBoxTipoDocumento(ctrl.carregarCmbBoxTipoDocumento());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTab = new javax.swing.JTabbedPane();
        paneCadastro = new javax.swing.JPanel();
        lblNomeTipoDocumento = new javax.swing.JLabel();
        txtNomeTipoDocumento = new javax.swing.JTextField();
        lblDescricaoTipoDocumento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescricaoTipoDocumentp = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        listTipoDocumento = new javax.swing.JList<>();
        btnSalvarTipoDocumento = new javax.swing.JButton();
        btnCancelarTipoDocumento = new javax.swing.JButton();
        paneConsulta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbTipoDocumento = new javax.swing.JComboBox<>();
        txtNomeTipoDocumentoConsulta = new javax.swing.JTextField();
        lblNomeTipoDocumentoConsulta = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaDescricaoTipoDocumentoConsulta = new javax.swing.JTextArea();
        lblDescricaoTipoDocumentoConsulta = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lblNomeTipoDocumento.setText("Nome");

        lblDescricaoTipoDocumento.setText("Descrição");

        txtAreaDescricaoTipoDocumentp.setColumns(20);
        txtAreaDescricaoTipoDocumentp.setRows(5);
        jScrollPane1.setViewportView(txtAreaDescricaoTipoDocumentp);

        jScrollPane2.setViewportView(listTipoDocumento);

        btnSalvarTipoDocumento.setText("Salvar");
        btnSalvarTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarTipoDocumentoActionPerformed(evt);
            }
        });

        btnCancelarTipoDocumento.setText("Cancelar");
        btnCancelarTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTipoDocumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneCadastroLayout = new javax.swing.GroupLayout(paneCadastro);
        paneCadastro.setLayout(paneCadastroLayout);
        paneCadastroLayout.setHorizontalGroup(
            paneCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCadastroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(paneCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricaoTipoDocumento)
                    .addGroup(paneCadastroLayout.createSequentialGroup()
                        .addComponent(lblNomeTipoDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneCadastroLayout.createSequentialGroup()
                            .addComponent(btnSalvarTipoDocumento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelarTipoDocumento))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        paneCadastroLayout.setVerticalGroup(
            paneCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeTipoDocumento)
                    .addComponent(txtNomeTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescricaoTipoDocumento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(paneCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarTipoDocumento)
                    .addComponent(btnCancelarTipoDocumento))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelTab.addTab("Cadastro", paneCadastro);

        jLabel1.setText("Tipo de Documento");

        lblNomeTipoDocumentoConsulta.setText("Nome");

        txtAreaDescricaoTipoDocumentoConsulta.setColumns(20);
        txtAreaDescricaoTipoDocumentoConsulta.setRows(5);
        jScrollPane3.setViewportView(txtAreaDescricaoTipoDocumentoConsulta);

        lblDescricaoTipoDocumentoConsulta.setText("Descrição");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneConsultaLayout = new javax.swing.GroupLayout(paneConsulta);
        paneConsulta.setLayout(paneConsultaLayout);
        paneConsultaLayout.setHorizontalGroup(
            paneConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneConsultaLayout.createSequentialGroup()
                .addGroup(paneConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneConsultaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(paneConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(paneConsultaLayout.createSequentialGroup()
                                .addGroup(paneConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescricaoTipoDocumentoConsulta)
                                    .addGroup(paneConsultaLayout.createSequentialGroup()
                                        .addComponent(lblNomeTipoDocumentoConsulta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNomeTipoDocumentoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(paneConsultaLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(26, 26, 26)
                                        .addComponent(cmbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 129, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneConsultaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOK)))
                .addContainerGap())
        );
        paneConsultaLayout.setVerticalGroup(
            paneConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeTipoDocumentoConsulta)
                    .addComponent(txtNomeTipoDocumentoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescricaoTipoDocumentoConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOK)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        panelTab.addTab("Consulta", paneConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTab, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTipoDocumentoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarTipoDocumentoActionPerformed

    private void btnSalvarTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarTipoDocumentoActionPerformed
        String nome = txtNomeTipoDocumento.getText();
        String desc = txtAreaDescricaoTipoDocumentp.getText();
        ctrl.cadastrarTipoDocumento(nome, desc);
    }//GEN-LAST:event_btnSalvarTipoDocumentoActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        ctrl.consultarTipoDocumento(cmbTipoDocumento.getSelectedItem().toString());
    }//GEN-LAST:event_btnOKActionPerformed


    public void iniciarInterfaceConsulta(){
        limparInterfaceConsulta();
        lblNomeTipoDocumentoConsulta.setEnabled(false);
        txtAreaDescricaoTipoDocumentoConsulta.setEnabled(false);
    }
    
    public void limparInterfaceConsulta(){
        lblNomeTipoDocumentoConsulta.setText("");
        txtAreaDescricaoTipoDocumentoConsulta.setText("");
    }
    
    public void preencherCamposConsulta(String nome, String desc){
        txtNomeTipoDocumentoConsulta.setText(nome);
        txtAreaDescricaoTipoDocumentoConsulta.setText(desc);
    }
    
    public void preencherCmbBoxTipoDocumento(List lista){
        if(lista != null){
            for(Object item : lista){
                cmbTipoDocumento.addItem(item.toString());
            }
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarTipoDocumento;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSalvarTipoDocumento;
    private javax.swing.JComboBox<String> cmbTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDescricaoTipoDocumento;
    private javax.swing.JLabel lblDescricaoTipoDocumentoConsulta;
    private javax.swing.JLabel lblNomeTipoDocumento;
    private javax.swing.JLabel lblNomeTipoDocumentoConsulta;
    private javax.swing.JList<String> listTipoDocumento;
    private javax.swing.JPanel paneCadastro;
    private javax.swing.JPanel paneConsulta;
    private javax.swing.JTabbedPane panelTab;
    private javax.swing.JTextArea txtAreaDescricaoTipoDocumentoConsulta;
    private javax.swing.JTextArea txtAreaDescricaoTipoDocumentp;
    private javax.swing.JTextField txtNomeTipoDocumento;
    private javax.swing.JTextField txtNomeTipoDocumentoConsulta;
    // End of variables declaration//GEN-END:variables
}
