/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cih.compartimento;

import cci.CICompartimento;
import java.util.ArrayList;

/**
 *
 * @author reida
 */
public class JPAlterarCompartimento extends javax.swing.JPanel {

    /**
     * Creates new form JPAlterarCompartimento
     */
    CICompartimento ctrl;
    public JPAlterarCompartimento(CICompartimento ctrl) {
        this.ctrl = ctrl;
        initComponents();
        inicializarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompartimentoPesquisa = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtIdentificaor = new javax.swing.JTextField();
        lblIdentificador = new javax.swing.JLabel();
        lblCapacidade = new javax.swing.JLabel();
        txtCapacidade = new javax.swing.JTextField();
        cmbTipoDocumento = new javax.swing.JComboBox<>();
        lblTipoDocumento = new javax.swing.JLabel();
        lblCompartimento = new javax.swing.JLabel();
        cmbCompartimento = new javax.swing.JComboBox<>();
        lblQtdCompartimento = new javax.swing.JLabel();
        spnQtdCompartimento = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        cmbCompartimentoPesquisa = new javax.swing.JComboBox<>();
        btnSelecionar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        setName("Alterar"); // NOI18N
        setPreferredSize(new java.awt.Dimension(548, 431));

        lblCompartimentoPesquisa.setText("Compartimento");

        lblNome.setText("Nome");

        lblIdentificador.setText("Identificador");

        lblCapacidade.setText("Capacidade");

        lblTipoDocumento.setText("Tipo de Documento");

        lblCompartimento.setText("Compartimento interno");

        lblQtdCompartimento.setText("Quantidade de compartimentos");

        spnQtdCompartimento.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCapacidade)
                            .addComponent(lblIdentificador)
                            .addComponent(lblNome)
                            .addComponent(lblTipoDocumento)
                            .addComponent(lblCompartimento))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtIdentificaor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(39, 39, 39)
                                    .addComponent(lblQtdCompartimento)
                                    .addGap(18, 18, 18)
                                    .addComponent(spnQtdCompartimento))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cmbCompartimento, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbTipoDocumento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(41, 41, 41)
                                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(txtCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCompartimentoPesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCompartimentoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelecionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAtualizar)))
                .addContainerGap(65, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCompartimentoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionar)
                    .addComponent(btnAtualizar)
                    .addComponent(lblCompartimentoPesquisa))
                .addGap(40, 40, 40)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificador)
                    .addComponent(txtIdentificaor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtdCompartimento)
                    .addComponent(spnQtdCompartimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCapacidade)
                    .addComponent(txtCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoDocumento))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCompartimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCompartimento)))
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addGap(110, 110, 110))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        inicializarCampos();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        if(!cmbCompartimentoPesquisa.getSelectedItem().toString().equals("Selecione")){
            Object[] compartimento;
            compartimento = ctrl.toArrayCompartimento(cmbCompartimentoPesquisa.getSelectedItem());
            preencherCampos(compartimento);
        }else
            ctrl.getCtrlP().getMensagens().exibirMenssagem(this, "Selecione um item");
            
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       ArrayList<String> erro = new ArrayList<String>();
        if(txtNome.getText().equals(""))
            erro.add("Nome");
        if(txtIdentificaor.getText().equals(""))
            erro.add("Identificador");
        if(txtCapacidade.getText().equals(""))
            erro.add("Capacidade");
        if(cmbTipoDocumento.getSelectedItem().toString().equals("Selecione"))
            erro.add("Tipo de Documento");
        if(cmbCompartimento.getSelectedItem().toString().equals("Selecione"))
            erro.add("Compartimento Interno");
        if(spnQtdCompartimento.getValue().toString().equals("0"))
            erro.add("Quantidade de compartimentos");
        if(ctrl.getCtrlP().getMensagens().validaCampos(this, erro))
            ctrl.alterarCompartimento(txtNome.getText(), txtIdentificaor.getText(), 
                    txtCapacidade.getText(), cmbTipoDocumento.getSelectedItem()
                    , cmbCompartimento.getSelectedItem(), spnQtdCompartimento.getValue().toString());
    }//GEN-LAST:event_btnAlterarActionPerformed


    private void preencherCampos(Object[] compartimento){
        txtNome.setText(compartimento[0].toString());
        txtIdentificaor.setText(compartimento[1].toString());
        txtCapacidade.setText(compartimento[2].toString());
        preencherCmbs();
        cmbTipoDocumento.setSelectedItem(compartimento[3]);
        cmbCompartimento.setSelectedItem(compartimento[4]);
    }
    
    public void preencherCmbs(){
        ctrl.preencherMobilia(cmbCompartimento);
        ctrl.preencherTipoDocumento(cmbTipoDocumento);
    }
    
    private void inicializarCampos(){
        cmbCompartimentoPesquisa.removeAllItems();
        cmbCompartimentoPesquisa.addItem("Selecione");
        ctrl.consultarCompartimento(null, cmbCompartimentoPesquisa);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JComboBox<String> cmbCompartimento;
    private javax.swing.JComboBox<String> cmbCompartimentoPesquisa;
    private javax.swing.JComboBox<String> cmbTipoDocumento;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCapacidade;
    private javax.swing.JLabel lblCompartimento;
    private javax.swing.JLabel lblCompartimentoPesquisa;
    private javax.swing.JLabel lblIdentificador;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQtdCompartimento;
    private javax.swing.JLabel lblTipoDocumento;
    private javax.swing.JSpinner spnQtdCompartimento;
    private javax.swing.JTextField txtCapacidade;
    private javax.swing.JTextField txtIdentificaor;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
