/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.menu;

import controlador.CIPrincipal;

/**
 *
 * @author reida
 */
public class MenuTipoDocumento extends javax.swing.JPanel {

    private CIPrincipal ctrlP;
    /**
     * Creates new form menuTipoDocumento
     */
    public MenuTipoDocumento(CIPrincipal ctrlP) {
        this.ctrlP = ctrlP;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastroDocumento = new javax.swing.JButton();
        lblTituloMenuTipoDocumento = new javax.swing.JLabel();
        btnRetornar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(124, 671));
        setLayout(null);

        btnCadastroDocumento.setText("Cadastro");
        add(btnCadastroDocumento);
        btnCadastroDocumento.setBounds(0, 20, 124, 95);

        lblTituloMenuTipoDocumento.setText("Tipo de Documento");
        add(lblTituloMenuTipoDocumento);
        lblTituloMenuTipoDocumento.setBounds(10, 0, 92, 14);

        btnRetornar.setText("Menu Principal");
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });
        add(btnRetornar);
        btnRetornar.setBounds(0, 637, 124, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
        ctrlP.alterarMenu(ctrlP.MENUPRINCIPAL);
    }//GEN-LAST:event_btnRetornarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroDocumento;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JLabel lblTituloMenuTipoDocumento;
    // End of variables declaration//GEN-END:variables
}
